# Load Data

In [1]:
import pandas as pd
import os

os.chdir('C:/Users/ASUS/Documents/Datasets')
df = pd.read_csv('cars.csv')
df

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,NaN,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,NaN,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,NaN,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

### Check Statistical Details

In [2]:
df.describe()

,id,Min.Price,Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight
count,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000,93.000000
mean,47.000000,17.125806,19.509677,21.898925,22.365591,29.086022,2.667742,143.827957,5280.645161,2332.204301,16.664516,5.086022,183.204301,103.946237,69.376344,38.956989,27.829670,13.890244,3072.903226
std,26.990739,8.746029,9.659430,11.030457,5.619812,5.331726,1.037363,52.374410,596.731690,496.506525,3.279370,1.038979,14.602382,6.819674,3.778986,3.223265,2.989072,2.997967,589.896510
min,1.000000,6.700000,7.400000,7.900000,15.000000,20.000000,1.000000,55.000000,3800.000000,1320.000000,9.200000,2.000000,141.000000,90.000000,60.000000,32.000000,19.000000,6.000000,1695.000000
25%,24.000000,10.800000,12.200000,14.700000,18.000000,26.000000,1.800000,103.000000,4800.000000,1985.000000,14.500000,4.000000,174.000000,98.000000,67.000000,37.000000,26.000000,12.000000,2620.000000
50%,47.000000,14.700000,17.700000,19.600000,21.000000,28.000000,2.400000,140.000000,5200.000000,2340.000000,16.400000,5.000000,183.000000,103.000000,69.000000,39.000000,27.500000,14.000000,3040.000000
75%,70.000000,20.300000,23.300000,25.300000,25.000000,31.000000,3.300000,170.000000,5750.000000,2565.000000,18.800000,6.000000,192.000000,110.000000,72.000000,41.000000,30.000000,15.000000,3525.000000
max,93.000000,45.400000,61.900000,80.000000,46.000000,50.000000,5.700000,300.000000,6500.000000,3755.000000,27.000000,8.000000,219.000000,119.000000,78.000000,45.000000,36.000000,22.000000,4105.000000

In [3]:
cat = []
con = []

for i in df.columns:
    if df[i].dtypes == 'object':
        cat.append(i)
    else:
        con.append(i)

In [4]:
cat

['Manufacturer',
 'Model',
 'Type',
 'AirBags',
 'DriveTrain',
 'Cylinders',
 'Man.trans.avail',
 'Origin',
 'Make']

In [5]:
con

['id',
 'Min.Price',
 'Price',
 'Max.Price',
 'MPG.city',
 'MPG.highway',
 'EngineSize',
 'Horsepower',
 'RPM',
 'Rev.per.mile',
 'Fuel.tank.capacity',
 'Passengers',
 'Length',
 'Wheelbase',
 'Width',
 'Turn.circle',
 'Rear.seat.room',
 'Luggage.room',
 'Weight']

### Select Categorical value for Target. (select Binary value)

In [6]:
# Manual Transmission version available
df['Man.trans.avail'].unique()

array(['Yes', 'No'], dtype=object)

In [7]:
df['Man.trans.avail'].value_counts()

Man.trans.avail
Yes    61
No     32
Name: count, dtype: int64

### create sub dataframe

In [8]:
df1 = df[['Price', 'Fuel.tank.capacity', 'RPM', 'Horsepower', 'Man.trans.avail']]
df1

    Price  Fuel.tank.capacity   RPM  Horsepower Man.trans.avail
0    15.9                13.2  6300         140             Yes
1    33.9                18.0  5500         200             Yes
2    29.1                16.9  5500         172             Yes
3    37.7                21.1  5500         172             Yes
4    30.0                21.1  5700         208             Yes
..    ...                 ...   ...         ...             ...
88   19.7                21.1  4500         109             Yes
89   20.0                18.5  5800         134             Yes
90   23.3                18.5  5800         178             Yes
91   22.7                15.8  5400         114             Yes
92   26.7                19.3  6200         168             Yes

[93 rows x 5 columns]

# Check missing data

In [9]:
df.isna().sum()

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags               37
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

In [10]:
df1.isna().sum()

Price                 0
Fuel.tank.capacity    0
RPM                   0
Horsepower            0
Man.trans.avail       0
dtype: int64

### define feature and targets

In [11]:
x = df1.drop(['Man.trans.avail'], axis = 1)
y = df1['Man.trans.avail']

In [12]:
x

    Price  Fuel.tank.capacity   RPM  Horsepower
0    15.9                13.2  6300         140
1    33.9                18.0  5500         200
2    29.1                16.9  5500         172
3    37.7                21.1  5500         172
4    30.0                21.1  5700         208
..    ...                 ...   ...         ...
88   19.7                21.1  4500         109
89   20.0                18.5  5800         134
90   23.3                18.5  5800         178
91   22.7                15.8  5400         114
92   26.7                19.3  6200         168

[93 rows x 4 columns]

In [13]:
y

0     Yes
1     Yes
2     Yes
3     Yes
4     Yes
     ...
88    Yes
89    Yes
90    Yes
91    Yes
92    Yes
Name: Man.trans.avail, Length: 93, dtype: object

# Preprocessing

In [14]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [15]:
# create objects of StandardScaler, LabelEncoder

ss = StandardScaler()
le = LabelEncoder()

In [16]:
# transform Feature Variable x

x1 = pd.DataFrame(ss.fit_transform(x), columns = ss.get_feature_names_out())
y1 = le.fit_transform(y)

In [17]:
# display x1
x1

       Price  Fuel.tank.capacity       RPM  Horsepower
0  -0.375720           -1.062184  1.717489   -0.073484
1   1.497844            0.409445  0.369586    1.078322
2   0.998227            0.072197  0.369586    0.540813
3   1.893374            1.359872  0.369586    0.540813
4   1.091905            1.359872  0.706562    1.231897
..       ...                 ...       ...         ...
88  0.019810            1.359872 -1.315292   -0.668585
89  0.051036            0.562740  0.875050   -0.188665
90  0.394523            0.562740  0.875050    0.655993
91  0.332071           -0.265051  0.201098   -0.572601
92  0.748418            0.808011  1.549001    0.464025

[93 rows x 4 columns]

In [18]:
# display y1
y1

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

# Split

In [19]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x1, y1, test_size = 0.2, random_state = 25)

In [22]:
x_train

       Price  Fuel.tank.capacity       RPM  Horsepower
13 -0.458990           -0.357028 -1.146804    0.310451
86  0.332071            0.961306 -0.472853   -0.111878
66  0.207167            0.562740 -0.135877    0.310451
25 -0.053051            1.022624 -0.472853   -0.035091
53 -0.823294           -0.663618  0.369586   -0.783765
..       ...                 ...       ...         ...
61 -0.958607           -1.062184  1.212025   -0.994930
15 -0.334085            1.022624 -0.809828    0.502419
90  0.394523            0.562740  0.875050    0.655993
62  0.685966            0.716035  1.212025    1.116716
4   1.091905            1.359872  0.706562    1.231897

[74 rows x 4 columns]

In [23]:
x_test

       Price  Fuel.tank.capacity       RPM  Horsepower
6   0.134306            0.409445 -0.809828    0.502419
58  4.412277            0.562740  0.369586    1.404668
67 -0.625529           -0.449005  1.212025    0.214467
52 -1.166781           -1.062184 -0.472853   -1.186898
82 -1.135555           -1.859316  1.212025   -1.417259
70  0.123897            0.409445 -0.809828    0.502419
46 -0.583894            0.164174  1.212025   -0.303846
63 -0.802476           -1.062184  1.212025   -0.649388
0  -0.375720           -1.062184  1.717489   -0.073484
35  0.040627            1.329213 -0.809828    0.022499
88  0.019810            1.359872 -1.315292   -0.668585
41 -0.771250           -1.460750  1.043537   -0.802962
84 -0.115503           -0.234393  0.201098   -0.169468
21  1.039862           -0.203734 -0.809828    0.060893
56  1.352122            1.022624  2.054464    2.134145
24 -0.646346           -0.203734 -0.809828   -0.841356
80 -0.896155           -0.234393 -0.135877   -1.033324
73 -0.875337           -0.449005 -0.135877   -0.649388
59 -0.563077           -1.706021  0.790806   -0.841356

In [24]:
x_test.shape

(19, 4)

In [25]:
y_train

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1])

In [26]:
y_test

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

# Model

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
# create object of LogisticRegression

lr = LogisticRegression()

#### fit model
fit(feature,target)

In [29]:
lr.fit(x_train, y_train)

LogisticRegression()

# Evaluation

In [31]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Training Data Evaluation

In [32]:
# create predicted value

y_pred_train = lr.predict(x_train)
y_pred_train

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0])

In [33]:
acc = accuracy_score(y_pred_train, y_train)

In [34]:
clf = classification_report(y_pred_train, y_train)

In [35]:
cnf = confusion_matrix(y_pred_train, y_train)

In [36]:
print('Accuracy:',acc, '\n', '-------------------------------------------------------', '\n')
print('Classification Report:\n',clf, '\n', '-------------------------------------------------------', '\n')
print('Confusion Matrix:\n',cnf, '\n', '-------------------------------------------------------', '\n')

Accuracy: 0.7837837837837838
 -------------------------------------------------------

Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.76      0.67        21
           1       0.89      0.79      0.84        53

    accuracy                           0.78        74
   macro avg       0.74      0.78      0.75        74
weighted avg       0.81      0.78      0.79        74

 -------------------------------------------------------

Confusion Matrix:
 [[16  5]
 [11 42]]
 -------------------------------------------------------

# Testing Data Evaluation

In [37]:
y_pred_test =lr.predict(x_test)
y_pred_test

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
acc1 = accuracy_score(y_pred_test,y_test)
clf1 = classification_report(y_pred_test,y_test)
cnf1 = confusion_matrix(y_pred_test,y_test)

In [39]:
print('Accuracy:',acc1, '\n', '-------------------------------------------------------', '\n')
print('Classification Report:\n',clf1, '\n', '-------------------------------------------------------', '\n')
print('Confusion Matrix:\n',cnf1, '\n', '-------------------------------------------------------', '\n')

Accuracy: 0.7368421052631579
 -------------------------------------------------------

Classification Report:
               precision    recall  f1-score   support

           0       0.40      0.50      0.44         4
           1       0.86      0.80      0.83        15

    accuracy                           0.74        19
   macro avg       0.63      0.65      0.64        19
weighted avg       0.76      0.74      0.75        19

 -------------------------------------------------------

Confusion Matrix:
 [[ 2  2]
 [ 3 12]]
 -------------------------------------------------------