## Data

In [1]:
# import libiries

import pandas as pd
import os

In [2]:
os.chdir('C:/Users/ASUS/Documents/Datasets')

In [3]:
df = pd.read_csv('cars93.csv')
df

,Unnamed: 0,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,Price Type
0,0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,...,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra,Cheap
1,1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,...,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend,Expensive
2,2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,...,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90,Expensive
3,3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,...,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100,Expensive
4,4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,...,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i,Expensive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,...,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan,Moderate
89,89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,...,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat,Moderate
90,90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,...,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado,Expensive
91,91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,...,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240,Expensive
92,92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,...,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850,Expensive

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 30 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          93 non-null     int64
 1   id                  93 non-null     int64
 2   Manufacturer        93 non-null     object
 3   Model               93 non-null     object
 4   Type                93 non-null     object
 5   Min.Price           93 non-null     float64
 6   Price               93 non-null     float64
 7   Max.Price           93 non-null     float64
 8   MPG.city            93 non-null     int64
 9   MPG.highway         93 non-null     int64
 10  AirBags             56 non-null     object
 11  DriveTrain          93 non-null     object
 12  Cylinders           93 non-null     object
 13  EngineSize          93 non-null     float64
 14  Horsepower          93 non-null     int64
 15  RPM                 93 non-null     int64
 16  Rev.per.mile        93 non-null     int64
 17  Man.trans.avail     93 non-null     object
 18  Fuel.tank.capacity  93 non-null     float64
 19  Passengers          93 non-null     int64
 20  Length              93 non-null     int64
 21  Wheelbase           93 non-null     int64
 22  Width               93 non-null     int64
 23  Turn.circle         93 non-null     int64
 24  Rear.seat.room      91 non-null     float64
 25  Luggage.room        82 non-null     float64
 26  Weight              93 non-null     int64
 27  Origin              93 non-null     object
 28  Make                93 non-null     object
 29  Price Type          93 non-null     object
dtypes: float64(7), int64(13), object(10)
memory usage: 21.9+ KB

In [5]:
# Dimensions of Data
df.shape

(93, 30)

In [6]:
# Statistical Information 
df.describe()

,Unnamed: 0,id,Min.Price,Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight
count,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000,93.000000
mean,46.000000,47.000000,17.125806,19.509677,21.898925,22.365591,29.086022,2.667742,143.827957,5280.645161,2332.204301,16.664516,5.086022,183.204301,103.946237,69.376344,38.956989,27.829670,13.890244,3072.903226
std,26.990739,26.990739,8.746029,9.659430,11.030457,5.619812,5.331726,1.037363,52.374410,596.731690,496.506525,3.279370,1.038979,14.602382,6.819674,3.778986,3.223265,2.989072,2.997967,589.896510
min,0.000000,1.000000,6.700000,7.400000,7.900000,15.000000,20.000000,1.000000,55.000000,3800.000000,1320.000000,9.200000,2.000000,141.000000,90.000000,60.000000,32.000000,19.000000,6.000000,1695.000000
25%,23.000000,24.000000,10.800000,12.200000,14.700000,18.000000,26.000000,1.800000,103.000000,4800.000000,1985.000000,14.500000,4.000000,174.000000,98.000000,67.000000,37.000000,26.000000,12.000000,2620.000000
50%,46.000000,47.000000,14.700000,17.700000,19.600000,21.000000,28.000000,2.400000,140.000000,5200.000000,2340.000000,16.400000,5.000000,183.000000,103.000000,69.000000,39.000000,27.500000,14.000000,3040.000000
75%,69.000000,70.000000,20.300000,23.300000,25.300000,25.000000,31.000000,3.300000,170.000000,5750.000000,2565.000000,18.800000,6.000000,192.000000,110.000000,72.000000,41.000000,30.000000,15.000000,3525.000000
max,92.000000,93.000000,45.400000,61.900000,80.000000,46.000000,50.000000,5.700000,300.000000,6500.000000,3755.000000,27.000000,8.000000,219.000000,119.000000,78.000000,45.000000,36.000000,22.000000,4105.000000

> Missing Data Handling

In [7]:
df.isna().sum()

Unnamed: 0             0
id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags               37
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
Price Type             0
dtype: int64

In [8]:
# treating missing values
for i in df.columns:
    if df[i].dtypes == 'object':
        m = df[i].mode()[0]
        df[i] = df[i].fillna(m)
    else:
        ma = df[i].mean()
        df[i] = df[i].fillna(ma)

In [9]:
# check for missing values
df.isna().sum()

Unnamed: 0            0
id                    0
Manufacturer          0
Model                 0
Type                  0
Min.Price             0
Price                 0
Max.Price             0
MPG.city              0
MPG.highway           0
AirBags               0
DriveTrain            0
Cylinders             0
EngineSize            0
Horsepower            0
RPM                   0
Rev.per.mile          0
Man.trans.avail       0
Fuel.tank.capacity    0
Passengers            0
Length                0
Wheelbase             0
Width                 0
Turn.circle           0
Rear.seat.room        0
Luggage.room          0
Weight                0
Origin                0
Make                  0
Price Type            0
dtype: int64

### Define Target

In [10]:
# indipendent variable

x = df.drop(['Price'], axis = 1)    # feature variable

# dependent variable

y = df['Price']      # Target variable

In [11]:
x

,Unnamed: 0,id,Manufacturer,Model,Type,Min.Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,Price Type
0,0,1,Acura,Integra,Small,12.9,18.8,25,31,Driver only,...,177,102,68,37,26.5,11.000000,2705,non-USA,Acura Integra,Cheap
1,1,2,Acura,Legend,Midsize,29.2,38.7,18,25,Driver & Passenger,...,195,115,71,38,30.0,15.000000,3560,non-USA,Acura Legend,Expensive
2,2,3,Audi,90,Compact,25.9,32.3,20,26,Driver only,...,180,102,67,37,28.0,14.000000,3375,non-USA,Audi 90,Expensive
3,3,4,Audi,100,Midsize,30.8,44.6,19,26,Driver only,...,193,106,70,37,31.0,17.000000,3405,non-USA,Audi 100,Expensive
4,4,5,BMW,535i,Midsize,23.7,36.2,22,30,Driver only,...,186,109,69,39,27.0,13.000000,3640,non-USA,BMW 535i,Expensive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,88,89,Volkswagen,Eurovan,Van,16.6,22.7,17,21,Driver only,...,187,115,72,38,34.0,13.890244,3960,non-USA,Volkswagen Eurovan,Moderate
89,89,90,Volkswagen,Passat,Compact,17.6,22.4,21,30,Driver only,...,180,103,67,35,31.5,14.000000,2985,non-USA,Volkswagen Passat,Moderate
90,90,91,Volkswagen,Corrado,Sporty,22.9,23.7,18,25,Driver only,...,159,97,66,36,26.0,15.000000,2810,non-USA,Volkswagen Corrado,Expensive
91,91,92,Volvo,240,Compact,21.8,23.5,21,28,Driver only,...,190,104,67,37,29.5,14.000000,2985,non-USA,Volvo 240,Expensive
92,92,93,Volvo,850,Midsize,24.8,28.5,20,28,Driver & Passenger,...,184,105,69,38,30.0,15.000000,3245,non-USA,Volvo 850,Expensive

In [12]:
y

0     15.9
1     33.9
2     29.1
3     37.7
4     30.0
      ...
88    19.7
89    20.0
90    23.3
91    22.7
92    26.7
Name: Price, Length: 93, dtype: float64

### Separate Data in Continuous and Categorical

In [13]:
cat = x.select_dtypes(include = 'object')
con = x.select_dtypes(exclude = 'object')

In [14]:
cat

,Manufacturer,Model,Type,AirBags,DriveTrain,Cylinders,Man.trans.avail,Origin,Make,Price Type
0,Acura,Integra,Small,Driver only,Front,4,Yes,non-USA,Acura Integra,Cheap
1,Acura,Legend,Midsize,Driver & Passenger,Front,6,Yes,non-USA,Acura Legend,Expensive
2,Audi,90,Compact,Driver only,Front,6,Yes,non-USA,Audi 90,Expensive
3,Audi,100,Midsize,Driver only,Front,6,Yes,non-USA,Audi 100,Expensive
4,BMW,535i,Midsize,Driver only,Rear,4,Yes,non-USA,BMW 535i,Expensive
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,Driver only,Front,5,Yes,non-USA,Volkswagen Eurovan,Moderate
89,Volkswagen,Passat,Compact,Driver only,Front,4,Yes,non-USA,Volkswagen Passat,Moderate
90,Volkswagen,Corrado,Sporty,Driver only,Front,6,Yes,non-USA,Volkswagen Corrado,Expensive
91,Volvo,240,Compact,Driver only,Rear,4,Yes,non-USA,Volvo 240,Expensive
92,Volvo,850,Midsize,Driver & Passenger,Front,5,Yes,non-USA,Volvo 850,Expensive

In [15]:
con

,Unnamed: 0,id,Min.Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight
0,0,1,12.9,18.8,25,31,1.8,140,6300,2890,13.2,5,177,102,68,37,26.5,11.000000,2705
1,1,2,29.2,38.7,18,25,3.2,200,5500,2335,18.0,5,195,115,71,38,30.0,15.000000,3560
2,2,3,25.9,32.3,20,26,2.8,172,5500,2280,16.9,5,180,102,67,37,28.0,14.000000,3375
3,3,4,30.8,44.6,19,26,2.8,172,5500,2535,21.1,6,193,106,70,37,31.0,17.000000,3405
4,4,5,23.7,36.2,22,30,3.5,208,5700,2545,21.1,4,186,109,69,39,27.0,13.000000,3640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,88,89,16.6,22.7,17,21,2.5,109,4500,2915,21.1,7,187,115,72,38,34.0,13.890244,3960
89,89,90,17.6,22.4,21,30,2.0,134,5800,2685,18.5,5,180,103,67,35,31.5,14.000000,2985
90,90,91,22.9,23.7,18,25,2.8,178,5800,2385,18.5,4,159,97,66,36,26.0,15.000000,2810
91,91,92,21.8,23.5,21,28,2.3,114,5400,2215,15.8,5,190,104,67,37,29.5,14.000000,2985
92,92,93,24.8,28.5,20,28,2.4,168,6200,2310,19.3,5,184,105,69,38,30.0,15.000000,3245

### Preprocessing

> Categorical Label Encoding

In [16]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# create object of LabelEncoder
le = LabelEncoder()

# create object of OneHotEncoder
oh = OneHotEncoder()

In [17]:
# display categorical columns
cat

,Manufacturer,Model,Type,AirBags,DriveTrain,Cylinders,Man.trans.avail,Origin,Make,Price Type
0,Acura,Integra,Small,Driver only,Front,4,Yes,non-USA,Acura Integra,Cheap
1,Acura,Legend,Midsize,Driver & Passenger,Front,6,Yes,non-USA,Acura Legend,Expensive
2,Audi,90,Compact,Driver only,Front,6,Yes,non-USA,Audi 90,Expensive
3,Audi,100,Midsize,Driver only,Front,6,Yes,non-USA,Audi 100,Expensive
4,BMW,535i,Midsize,Driver only,Rear,4,Yes,non-USA,BMW 535i,Expensive
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,Driver only,Front,5,Yes,non-USA,Volkswagen Eurovan,Moderate
89,Volkswagen,Passat,Compact,Driver only,Front,4,Yes,non-USA,Volkswagen Passat,Moderate
90,Volkswagen,Corrado,Sporty,Driver only,Front,6,Yes,non-USA,Volkswagen Corrado,Expensive
91,Volvo,240,Compact,Driver only,Rear,4,Yes,non-USA,Volvo 240,Expensive
92,Volvo,850,Midsize,Driver & Passenger,Front,5,Yes,non-USA,Volvo 850,Expensive

In [18]:
df['Manufacturer'].nunique()

32

In [19]:
df['Model'].nunique()

93

In [20]:
cat1 = cat.apply(le.fit_transform)
cat1

,Manufacturer,Model,Type,AirBags,DriveTrain,Cylinders,Man.trans.avail,Origin,Make,Price Type
0,0,48,3,1,1,1,1,1,0,0
1,0,55,2,0,1,3,1,1,1,1
2,1,8,0,1,1,3,1,1,3,1
3,1,0,2,1,1,3,1,1,2,1
4,2,5,2,1,2,1,1,1,4,1
...,...,...,...,...,...,...,...,...,...,...
88,30,41,5,1,1,2,1,1,88,2
89,30,64,0,1,1,1,1,1,90,2
90,30,28,4,1,1,3,1,1,87,1
91,31,2,0,1,2,1,1,1,91,1
92,31,7,2,0,1,2,1,1,92,1

In [21]:
cat2 = pd.DataFrame(oh.fit_transform(cat))
cat2

                                                    0
0     (0, 0)\t1.0\n  (0, 80)\t1.0\n  (0, 128)\t1.0...
1     (0, 0)\t1.0\n  (0, 87)\t1.0\n  (0, 127)\t1.0...
2     (0, 1)\t1.0\n  (0, 40)\t1.0\n  (0, 125)\t1.0...
3     (0, 1)\t1.0\n  (0, 32)\t1.0\n  (0, 127)\t1.0...
4     (0, 2)\t1.0\n  (0, 37)\t1.0\n  (0, 127)\t1.0...
..                                                ...
88    (0, 30)\t1.0\n  (0, 73)\t1.0\n  (0, 130)\t1....
89    (0, 30)\t1.0\n  (0, 96)\t1.0\n  (0, 125)\t1....
90    (0, 30)\t1.0\n  (0, 60)\t1.0\n  (0, 129)\t1....
91    (0, 31)\t1.0\n  (0, 34)\t1.0\n  (0, 125)\t1....
92    (0, 31)\t1.0\n  (0, 39)\t1.0\n  (0, 127)\t1....

[93 rows x 1 columns]

In [22]:
cat2 = pd.DataFrame(oh.fit_transform(cat).toarray(), columns=oh.get_feature_names_out())
cat2

,Manufacturer_Acura,Manufacturer_Audi,Manufacturer_BMW,Manufacturer_Buick,Manufacturer_Cadillac,Manufacturer_Chevrolet,Manufacturer_Chrylser,Manufacturer_Chrysler,Manufacturer_Dodge,Manufacturer_Eagle,...,Make_Toyota Tercel,Make_Volkswagen Corrado,Make_Volkswagen Eurovan,Make_Volkswagen Fox,Make_Volkswagen Passat,Make_Volvo 240,Make_Volvo 850,Price Type_Cheap,Price Type_Expensive,Price Type_Moderate
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
89,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
91,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
92,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

### Numerical data Standardization

In [23]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [24]:
# create objects of Standard scaler and MinMaxScaler
ss = StandardScaler()
mn = MinMaxScaler()

In [25]:
con

,Unnamed: 0,id,Min.Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight
0,0,1,12.9,18.8,25,31,1.8,140,6300,2890,13.2,5,177,102,68,37,26.5,11.000000,2705
1,1,2,29.2,38.7,18,25,3.2,200,5500,2335,18.0,5,195,115,71,38,30.0,15.000000,3560
2,2,3,25.9,32.3,20,26,2.8,172,5500,2280,16.9,5,180,102,67,37,28.0,14.000000,3375
3,3,4,30.8,44.6,19,26,2.8,172,5500,2535,21.1,6,193,106,70,37,31.0,17.000000,3405
4,4,5,23.7,36.2,22,30,3.5,208,5700,2545,21.1,4,186,109,69,39,27.0,13.000000,3640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,88,89,16.6,22.7,17,21,2.5,109,4500,2915,21.1,7,187,115,72,38,34.0,13.890244,3960
89,89,90,17.6,22.4,21,30,2.0,134,5800,2685,18.5,5,180,103,67,35,31.5,14.000000,2985
90,90,91,22.9,23.7,18,25,2.8,178,5800,2385,18.5,4,159,97,66,36,26.0,15.000000,2810
91,91,92,21.8,23.5,21,28,2.3,114,5400,2215,15.8,5,190,104,67,37,29.5,14.000000,2985
92,92,93,24.8,28.5,20,28,2.4,168,6200,2310,19.3,5,184,105,69,38,30.0,15.000000,3245

### Standardization in continuous values

In [26]:
con1 = pd.DataFrame(ss.fit_transform(con), columns = ss.get_feature_names_out())
con1

,Unnamed: 0,id,Min.Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight
0,-1.713526,-1.713526,-0.485787,-0.282465,0.471312,0.360925,-0.841022,-0.073484,1.717489,1.129530,-1.062184,-0.083243,-0.427186,-0.286932,-0.366184,-0.610436,-0.452197,-1.033015,-0.627055
1,-1.676275,-1.676275,1.388017,1.531409,-0.781032,-0.770514,0.515869,1.078322,0.369586,0.005661,0.409445,-0.083243,0.812171,1.629649,0.431983,-0.298510,0.738090,0.396643,0.830208
2,-1.639025,-1.639025,1.008658,0.948052,-0.423219,-0.581941,0.128186,0.540813,0.369586,-0.105713,0.072197,-0.083243,-0.220626,-0.286932,-0.632239,-0.610436,0.057926,0.039228,0.514894
3,-1.601774,-1.601774,1.571949,2.069191,-0.602126,-0.581941,0.128186,0.540813,0.369586,0.410659,1.359872,0.884457,0.674465,0.302785,0.165927,-0.610436,1.078172,1.111472,0.566026
4,-1.564523,-1.564523,0.755752,1.303535,-0.065407,0.172352,0.806631,1.231897,0.706562,0.430909,1.359872,-1.050944,0.192493,0.745073,-0.100128,0.013416,-0.282156,-0.318186,0.966560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,1.564523,1.564523,-0.060445,0.073018,-0.959938,-1.524806,-0.162577,-0.668585,-1.315292,1.180155,1.359872,1.852158,0.261346,1.629649,0.698038,-0.298510,2.098419,0.000000,1.511968
89,1.601774,1.601774,0.054512,0.045673,-0.244313,0.172352,-0.647181,-0.188665,0.875050,0.714407,0.562740,-0.083243,-0.220626,-0.139503,-0.632239,-1.234288,1.248213,0.039228,-0.149822
90,1.639025,1.639025,0.663786,0.164167,-0.781032,-0.770514,0.128186,0.655993,0.875050,0.106911,0.562740,-1.050944,-1.666543,-1.024079,-0.898295,-0.922362,-0.622238,0.396643,-0.448092
91,1.676275,1.676275,0.537333,0.145937,-0.244313,-0.204794,-0.356418,-0.572601,0.201098,-0.237337,-0.265051,-0.083243,0.467905,0.007926,-0.632239,-0.610436,0.568049,0.039228,-0.149822
92,1.713526,1.713526,0.882205,0.601684,-0.423219,-0.204794,-0.259498,0.464025,1.549001,-0.044963,0.808011,-0.083243,0.054786,0.155356,-0.100128,-0.298510,0.738090,0.396643,0.293322

In [27]:
con1['Horsepower'].std()

1.0054200938997546

In [28]:
# using MinMAxScaler

con2 = pd.DataFrame(mn.fit_transform(con), columns=mn.get_feature_names_out())
con2

,Unnamed: 0,id,Min.Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight
0,0.000000,0.000000,0.160207,0.151179,0.322581,0.366667,0.170213,0.346939,0.925926,0.644764,0.224719,0.500000,0.461538,0.413793,0.444444,0.384615,0.441176,0.31250,0.419087
1,0.010870,0.010870,0.581395,0.427184,0.096774,0.166667,0.468085,0.591837,0.629630,0.416838,0.494382,0.500000,0.692308,0.862069,0.611111,0.461538,0.647059,0.56250,0.773859
2,0.021739,0.021739,0.496124,0.338419,0.161290,0.200000,0.382979,0.477551,0.629630,0.394251,0.432584,0.500000,0.500000,0.413793,0.388889,0.384615,0.529412,0.50000,0.697095
3,0.032609,0.032609,0.622739,0.509015,0.129032,0.200000,0.382979,0.477551,0.629630,0.498973,0.668539,0.666667,0.666667,0.551724,0.555556,0.384615,0.705882,0.68750,0.709544
4,0.043478,0.043478,0.439276,0.392510,0.225806,0.333333,0.531915,0.624490,0.703704,0.503080,0.668539,0.333333,0.576923,0.655172,0.500000,0.538462,0.470588,0.43750,0.807054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,0.956522,0.956522,0.255814,0.205270,0.064516,0.033333,0.319149,0.220408,0.259259,0.655031,0.668539,0.833333,0.589744,0.862069,0.666667,0.461538,0.882353,0.49314,0.939834
89,0.967391,0.967391,0.281654,0.201110,0.193548,0.333333,0.212766,0.322449,0.740741,0.560575,0.522472,0.500000,0.500000,0.448276,0.388889,0.230769,0.735294,0.50000,0.535270
90,0.978261,0.978261,0.418605,0.219140,0.096774,0.166667,0.382979,0.502041,0.740741,0.437372,0.522472,0.333333,0.230769,0.241379,0.333333,0.307692,0.411765,0.56250,0.462656
91,0.989130,0.989130,0.390181,0.216366,0.193548,0.266667,0.276596,0.240816,0.592593,0.367556,0.370787,0.500000,0.628205,0.482759,0.388889,0.384615,0.617647,0.50000,0.535270
92,1.000000,1.000000,0.467700,0.285714,0.161290,0.266667,0.297872,0.461224,0.888889,0.406571,0.567416,0.500000,0.551282,0.517241,0.500000,0.461538,0.647059,0.56250,0.643154

## Join Dataframes

In [29]:
x1 = con1.join(cat1)

In [30]:
x1

,Unnamed: 0,id,Min.Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,...,Manufacturer,Model,Type,AirBags,DriveTrain,Cylinders,Man.trans.avail,Origin,Make,Price Type
0,-1.713526,-1.713526,-0.485787,-0.282465,0.471312,0.360925,-0.841022,-0.073484,1.717489,1.129530,...,0,48,3,1,1,1,1,1,0,0
1,-1.676275,-1.676275,1.388017,1.531409,-0.781032,-0.770514,0.515869,1.078322,0.369586,0.005661,...,0,55,2,0,1,3,1,1,1,1
2,-1.639025,-1.639025,1.008658,0.948052,-0.423219,-0.581941,0.128186,0.540813,0.369586,-0.105713,...,1,8,0,1,1,3,1,1,3,1
3,-1.601774,-1.601774,1.571949,2.069191,-0.602126,-0.581941,0.128186,0.540813,0.369586,0.410659,...,1,0,2,1,1,3,1,1,2,1
4,-1.564523,-1.564523,0.755752,1.303535,-0.065407,0.172352,0.806631,1.231897,0.706562,0.430909,...,2,5,2,1,2,1,1,1,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,1.564523,1.564523,-0.060445,0.073018,-0.959938,-1.524806,-0.162577,-0.668585,-1.315292,1.180155,...,30,41,5,1,1,2,1,1,88,2
89,1.601774,1.601774,0.054512,0.045673,-0.244313,0.172352,-0.647181,-0.188665,0.875050,0.714407,...,30,64,0,1,1,1,1,1,90,2
90,1.639025,1.639025,0.663786,0.164167,-0.781032,-0.770514,0.128186,0.655993,0.875050,0.106911,...,30,28,4,1,1,3,1,1,87,1
91,1.676275,1.676275,0.537333,0.145937,-0.244313,-0.204794,-0.356418,-0.572601,0.201098,-0.237337,...,31,2,0,1,2,1,1,1,91,1
92,1.713526,1.713526,0.882205,0.601684,-0.423219,-0.204794,-0.259498,0.464025,1.549001,-0.044963,...,31,7,2,0,1,2,1,1,92,1

In [31]:
x2 = con2.join(cat2)

In [32]:
x2

,Unnamed: 0,id,Min.Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,...,Make_Toyota Tercel,Make_Volkswagen Corrado,Make_Volkswagen Eurovan,Make_Volkswagen Fox,Make_Volkswagen Passat,Make_Volvo 240,Make_Volvo 850,Price Type_Cheap,Price Type_Expensive,Price Type_Moderate
0,0.000000,0.000000,0.160207,0.151179,0.322581,0.366667,0.170213,0.346939,0.925926,0.644764,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.010870,0.010870,0.581395,0.427184,0.096774,0.166667,0.468085,0.591837,0.629630,0.416838,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.021739,0.021739,0.496124,0.338419,0.161290,0.200000,0.382979,0.477551,0.629630,0.394251,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.032609,0.032609,0.622739,0.509015,0.129032,0.200000,0.382979,0.477551,0.629630,0.498973,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.043478,0.043478,0.439276,0.392510,0.225806,0.333333,0.531915,0.624490,0.703704,0.503080,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,0.956522,0.956522,0.255814,0.205270,0.064516,0.033333,0.319149,0.220408,0.259259,0.655031,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
89,0.967391,0.967391,0.281654,0.201110,0.193548,0.333333,0.212766,0.322449,0.740741,0.560575,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
90,0.978261,0.978261,0.418605,0.219140,0.096774,0.166667,0.382979,0.502041,0.740741,0.437372,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
91,0.989130,0.989130,0.390181,0.216366,0.193548,0.266667,0.276596,0.240816,0.592593,0.367556,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
92,1.000000,1.000000,0.467700,0.285714,0.161290,0.266667,0.297872,0.461224,0.888889,0.406571,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

## Split

In [33]:
from sklearn.model_selection import train_test_split

> generating training and test data

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x1,y,test_size = 0.2, random_state = 30)

In [35]:
# training data (feature variables)
x_train

,Unnamed: 0,id,Min.Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,...,Manufacturer,Model,Type,AirBags,DriveTrain,Cylinders,Man.trans.avail,Origin,Make,Price Type
80,1.266519,1.266519,-0.761685,-0.966086,0.471312,0.172352,-0.841022,-1.033324,-0.135877,2.111649,...,27,56,3,1,0,1,1,1,81,0
72,0.968515,0.968515,-1.026087,-1.093695,1.544751,2.246656,-1.034864,-1.340472,0.538074,1.615527,...,24,52,3,1,1,1,1,0,75,0
48,0.074501,0.074501,1.192590,0.592569,-0.781032,-0.959087,0.322027,0.790371,-0.135877,-0.014589,...,15,37,2,1,1,3,1,1,48,1
43,-0.111752,-0.111752,-1.187027,-1.157500,1.186938,0.738071,-1.131784,-1.206095,0.369586,0.765032,...,13,42,3,1,1,1,1,1,44,0
56,0.372506,0.372506,1.767376,0.966282,-0.959938,-0.770514,-1.325626,2.134145,2.054464,-0.014589,...,17,71,4,1,2,5,1,1,56,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12,-1.266519,-1.266519,-0.658223,-0.956971,0.471312,0.926644,-0.453339,-0.649388,-0.135877,0.673908,...,5,29,0,1,1,1,1,0,15,0
90,1.639025,1.639025,0.663786,0.164167,-0.781032,-0.770514,0.128186,0.655993,0.875050,0.106911,...,30,28,4,1,1,3,1,1,87,1
45,-0.037251,-0.037251,-0.922625,-0.993431,0.650219,0.926644,-1.131784,-0.994930,0.453830,0.420784,...,13,76,4,1,1,1,1,1,45,0
92,1.713526,1.713526,0.882205,0.601684,-0.423219,-0.204794,-0.259498,0.464025,1.549001,-0.044963,...,31,7,2,0,1,2,1,1,92,1
37,-0.335255,-0.335255,0.341905,-0.018132,-0.781032,-0.581941,1.872759,0.886355,-1.820755,-1.857328,...,10,32,1,1,2,4,0,0,31,2

In [36]:
# feature (test data)
x_test

,Unnamed: 0,id,Min.Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,...,Manufacturer,Model,Type,AirBags,DriveTrain,Cylinders,Man.trans.avail,Origin,Make,Price Type
38,-0.298004,-0.298004,-1.198523,-1.084580,4.228346,3.943814,-1.616388,-1.705211,0.706562,2.881145,...,11,61,3,1,1,0,1,1,38,0
32,-0.521508,-0.521508,-0.773181,-0.884052,-0.065407,-0.393368,-0.356418,-0.918143,-1.820755,0.957406,...,10,89,0,1,1,1,1,0,37,0
60,0.521508,0.521508,-0.255873,-0.637948,-0.602126,-0.581941,1.097393,-0.073484,-2.494706,-1.219457,...,19,31,2,1,2,3,0,0,60,0
82,1.341020,1.341020,-1.129548,-1.084580,2.976002,2.623802,-1.325626,-1.417259,1.212025,2.081275,...,28,87,3,1,1,0,1,1,82,0
8,-1.415521,-1.415521,1.054641,0.401156,-0.602126,-0.393368,1.097393,0.502419,-0.809828,-1.300456,...,3,72,2,1,1,3,0,0,7,1
75,1.080266,1.080266,-0.198394,-0.027247,-0.602126,-0.393368,0.709710,1.078322,-0.472853,-0.895459,...,24,46,2,1,1,3,1,0,74,2
0,-1.713526,-1.713526,-0.485787,-0.282465,0.471312,0.360925,-0.841022,-0.073484,1.717489,1.129530,...,0,48,3,1,1,1,1,1,0,0
71,0.931264,0.931264,-0.658223,-0.410075,0.113500,0.172352,-0.841022,-0.994930,-0.472853,0.056286,...,23,50,4,1,0,1,1,0,71,0
52,0.223503,0.223503,-1.118053,-1.166615,1.186938,1.492363,-1.034864,-1.186898,-0.472853,0.076536,...,17,4,3,1,1,1,1,1,52,0
59,0.484257,0.484257,-0.439804,-0.628833,0.113500,-0.581941,-1.034864,-0.841356,0.790806,0.289160,...,19,18,4,1,1,1,1,0,59,0
73,1.005765,1.005765,-0.888138,-0.829362,0.113500,0.360925,-0.647181,-0.649388,-0.135877,0.673908,...,24,86,0,1,1,1,1,0,76,0
10,-1.341020,-1.341020,2.342163,1.896007,-1.138845,-0.770514,1.872759,2.902017,1.212025,-0.703085,...,4,78,2,0,1,4,0,0,10,1
42,-0.149002,-0.149002,-0.382326,-0.063707,0.292406,0.360925,-0.453339,-0.073484,0.538074,0.562533,...,12,10,0,0,1,1,1,1,40,2
34,-0.447007,-0.447007,-0.497283,-0.610603,0.292406,0.172352,-0.647181,-0.553404,0.369586,0.015786,...,10,67,4,1,1,1,1,0,35,0
4,-1.564523,-1.564523,0.755752,1.303535,-0.065407,0.172352,0.806631,1.231897,0.706562,0.430909,...,2,5,2,1,2,1,1,1,4,1
79,1.229268,1.229268,-1.129548,-1.130155,1.902563,1.492363,-1.422547,-1.359669,0.538074,1.099155,...,27,49,3,1,0,0,1,1,79,0
24,-0.819512,-0.819512,-0.600745,-0.656178,-0.065407,-0.393368,-0.162577,-0.841356,-0.809828,0.410659,...,8,82,0,1,1,1,1,0,26,0
21,-0.931264,-0.931264,1.422504,0.692834,-0.423219,-0.581941,0.612789,0.060893,-0.809828,-1.108083,...,7,47,1,1,1,3,0,0,20,1
1,-1.676275,-1.676275,1.388017,1.531409,-0.781032,-0.770514,0.515869,1.078322,0.369586,0.005661,...,0,55,2,0,1,3,1,1,1,1

In [37]:
y_train

80    10.9
72     9.0
48    28.0
43     8.0
56    32.5
      ...
12    11.4
90    23.3
45    10.0
92    26.7
37    20.9
Name: Price, Length: 74, dtype: float64

In [38]:
y_test

38     8.4
32    11.3
60    14.9
82     8.6
8     26.3
75    18.5
0     15.9
71    14.4
52     8.3
59    14.1
73    11.1
10    40.1
42    17.5
34    14.0
4     30.0
79     8.4
24    13.3
21    29.5
1     33.9
Name: Price, dtype: float64

## Model Building

In [39]:
from sklearn.linear_model import LinearRegression

In [43]:
# create object of Linear Regression
la = LinearRegression()

In [44]:
# fit model
# linearRegression.fit(feature_train,target_train)
la.fit(x_train, y_train)

LinearRegression()

In [45]:
#check intercept
la.intercept_

19.455238308076318

In [46]:
# check coefficient
la.coef_

array([ 2.32086206e+10, -2.32086206e+10,  4.35409982e+00,  5.48447744e+00,
        2.90878881e-02, -2.67813596e-02, -2.25378947e-02, -8.05325990e-03,
       -9.49460488e-03, -1.11744763e-02,  2.59129101e-03, -3.05919146e-03,
        1.07667209e-02,  3.42593341e-03, -1.26403675e-02,  1.30817228e-02,
       -2.82978554e-05, -2.52732635e-03,  1.50021911e-03,  9.06944275e-04,
        5.04255295e-05, -8.53925943e-03, -8.27170897e-03, -2.95757502e-03,
        1.65505707e-02,  3.10520381e-02, -1.74984336e-03,  4.65393066e-04,
       -5.49945235e-03])

## Evaluation

In [47]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

> Training Data Evaluation

In [48]:
# generate prediction
y_pred_train = la.predict(x_train)

In [49]:
y_pred_train

array([10.90302862,  9.02786626, 27.97869915,  8.00734806, 32.52527215,
       19.5199781 , 11.79503406, 16.29253042, 22.76396703, 19.65938353,
       15.80669585, 19.32323844, 18.38334203,  7.39168119, 18.3898916 ,
       16.5034744 , 18.20413445, 47.89167378, 15.59326006, 15.71262536,
       18.97467662,  9.21558071, 24.39917789, 31.94358835, 61.88978023,
       34.6560424 , 12.47342519, 36.11903409, 22.68890063,  9.96928683,
       13.49185653, 10.11290762, 21.51851764, 19.80840346, 15.86985802,
       19.49203323, 11.06916555, 12.2027775 , 19.11661222, 15.90534925,
       34.31218653, 15.10949875, 20.18907583,  9.09810272, 16.32096085,
       13.39989341, 20.70108704, 15.68486149, 28.70832379,  9.80137172,
       25.77209923, 26.15318957, 20.78198998, 16.61200293, 17.71836059,
       38.00238858, 19.91925956, 10.30702937, 19.99917968, 35.17646763,
       19.08010323, 23.72729968, 12.0998736 , 37.69312307, 13.85975763,
       18.78671143, 11.59531777, 29.12170293, 11.29607134, 11.40619392,
       23.28536934, 10.02759918, 26.66629738, 20.89712416])

In [50]:
y_train

80    10.9
72     9.0
48    28.0
43     8.0
56    32.5
      ...
12    11.4
90    23.3
45    10.0
92    26.7
37    20.9
Name: Price, Length: 74, dtype: float64

In [51]:
# Error
y_train-y_pred_train

80   -0.003029
72   -0.027866
48    0.021301
43   -0.007348
56   -0.025272
        ...
12   -0.006194
90    0.014631
45   -0.027599
92    0.033703
37    0.002876
Name: Price, Length: 74, dtype: float64

In [52]:
# mean_squared_error(actual,predicted)
mse = mean_squared_error(y_train, y_pred_train)
mae = mean_absolute_error(y_train, y_pred_train)
r2_score1 = r2_score(y_train, y_pred_train)
rmse = mse**0.5

In [53]:
print("Mean_Squared_Error",mse)
print("Mean Absolute Error",mae)
print("Root Mean Squared Error",rmse)
print("R2 Score",r2_score1)

Mean_Squared_Error 0.00042534359957061994
Mean Absolute Error 0.015915360579169518
Root Mean Squared Error 0.020623859958083014
R2 Score 0.9999954315528011

> Testing Data Evaluation

In [54]:
# linearRegression(testData/test feature variable)
y_pred_test = la.predict(x_test)

In [55]:
y_pred_test

array([ 8.3138221 , 11.34160405, 14.91460543,  8.63494359, 26.28755671,
       18.5218933 , 15.80678854, 14.42465633,  8.23623749, 14.16179274,
       11.14021753, 40.06730147, 17.52550765, 13.98457655, 29.89485066,
        8.39159711, 13.33170383, 29.54559994, 33.9540977 ])

In [56]:
y_test

38     8.4
32    11.3
60    14.9
82     8.6
8     26.3
75    18.5
0     15.9
71    14.4
52     8.3
59    14.1
73    11.1
10    40.1
42    17.5
34    14.0
4     30.0
79     8.4
24    13.3
21    29.5
1     33.9
Name: Price, dtype: float64

In [57]:
y_test-y_pred_test

38    0.086178
32   -0.041604
60   -0.014605
82   -0.034944
8     0.012443
75   -0.021893
0     0.093211
71   -0.024656
52    0.063763
59   -0.061793
73   -0.040218
10    0.032699
42   -0.025508
34    0.015423
4     0.105149
79    0.008403
24   -0.031704
21   -0.045600
1    -0.054098
Name: Price, dtype: float64

In [58]:
mse=mean_squared_error(y_test,y_pred_test)
mae=mean_absolute_error(y_test,y_pred_test)
r2_score1=r2_score(y_test,y_pred_test)
rmse=mse**0.5

In [59]:
print("Mean_Squared_Error",mse)
print("Mean Absolute Error",mae)
print("Root Mean Squared Error",rmse)
print("R2 Score",r2_score1)

Mean_Squared_Error 0.0025852406374382714
Mean Absolute Error 0.04283639247474378
Root Mean Squared Error 0.05084526170095176
R2 Score 0.9999697867993464